### ISSUE TITLE
Probleme java

### ISSUE THREAD

**Issue by BreakingVap** [anthonyraymond/joal#113]
Bonjour, j'ai essayé d'utiliser votre outil sous mac, en ligne de commande en ayant installé java 8.

Voici les lignes d'erreurs 

[WARN ] 2020-12-27 22:53:34.468 [   annnouncer-0] o.a.j.c.t.c.a.Announcer: #Ã,ÄJÃW2AÅ`Dä has failed to announce
com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:66)
	at org.araymond.joal.core.ttorrent.client.announcer.Announcer.announce(Announcer.java:64)
	at org.araymond.joal.core.ttorrent.client.announcer.request.AnnouncerExecutor.lambda$execute$0(AnnouncerExecutor.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:102)
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:53)
	... 6 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 109.235.50.166:2710 [/109.235.50.166] failed: Operation timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:98)
	... 7 more
Caused by: java.net.ConnectException: Operation timed out
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 18 more

**Comment by BreakingVap** [comment]
j'ai relancé et maintenant ca me bloque sur ca, plus rien ne se passe et je ne vois pas mon ratio changé : 

[INFO ] 2020-12-27 23:33:08.390 [           main] o.a.j.c.t.c.ConnectionHandler: Listening for incoming peer connections on port 49164.
[INFO ] 2020-12-27 23:33:08.393 [           main] o.a.j.c.t.c.ConnectionHandler: Fetching ip from: http://ident.me/
[INFO ] 2020-12-27 23:33:08.501 [           main] o.a.j.c.t.c.ConnectionHandler: Successfully fetch public IP address: 93.11.181.161
[INFO ] 2020-12-27 23:33:08.501 [           main] o.a.j.c.t.c.ConnectionHandler: Ip reported to tracker will be: 93.11.181.161
[INFO ] 2020-12-27 23:33:08.506 [           main] o.a.j.c.t.w.TorrentFileProvider: Torrent file addition detected, hot creating file: /Users/ItaliaStylz/joal-conf/torrents/Motherless.Brooklyn.2019.MULTi.1080p.HDLight.x264.AC3-TOXIC.mkv.torrent
[INFO ] 2020-12-27 23:33:08.513 [           main] c.t.t.c.Torrent: Single-file torrent information:
[INFO ] 2020-12-27 23:33:08.513 [           main] c.t.t.c.Torrent:   Torrent name: Motherless.Brooklyn.2019.MULTi.1080p.HDLight.x264.AC3-TOXIC.mkv
[INFO ] 2020-12-27 23:33:08.513 [           main] c.t.t.c.Torrent:   Announced at:
[INFO ] 2020-12-27 23:33:08.513 [           main] c.t.t.c.Torrent:      1. http://tracker.yggtracker.cc:8080/nvPASB1sprU3Vx3n9EtlA3gJjiUga19a/announce
[INFO ] 2020-12-27 23:33:08.513 [           main] c.t.t.c.Torrent:   Created on..: 2020-12-27T16:30:12.000+0100
[INFO ] 2020-12-27 23:33:08.514 [           main] c.t.t.c.Torrent:   Created by..: YggTorrent
[INFO ] 2020-12-27 23:33:08.514 [           main] c.t.t.c.Torrent:   Pieces......: 861 piece(s) (4194304 byte(s)/piece)
[INFO ] 2020-12-27 23:33:08.514 [           main] c.t.t.c.Torrent:   Total size..: 3 608 760 794 byte(s)
[INFO ] 2020-12-27 23:33:08.515 [           main] o.a.j.c.t.w.TorrentFileProvider: Torrent file addition detected, hot creating file: /Users/ItaliaStylz/joal-conf/torrents/Mulan.2020.MULTi.TRUEFRENCH.1080p.WEBRip.x264-TOXIC.mkv.torrent
[INFO ] 2020-12-27 23:33:08.516 [           main] c.t.t.c.Torrent: Single-file torrent information:
[INFO ] 2020-12-27 23:33:08.516 [           main] c.t.t.c.Torrent:   Torrent name: Mulan.2020.MULTi.TRUEFRENCH.1080p.WEBRip.x264-TOXIC.mkv
[INFO ] 2020-12-27 23:33:08.516 [           main] c.t.t.c.Torrent:   Announced at:
[INFO ] 2020-12-27 23:33:08.516 [           main] c.t.t.c.Torrent:      1. http://tracker.yggtracker.cc:8080/nvPASB1sprU3Vx3n9EtlA3gJjiUga19a/announce
[INFO ] 2020-12-27 23:33:08.516 [           main] c.t.t.c.Torrent:   Created on..: 2020-12-27T22:17:32.000+0100
[INFO ] 2020-12-27 23:33:08.516 [           main] c.t.t.c.Torrent:   Created by..: YggTorrent
[INFO ] 2020-12-27 23:33:08.516 [           main] c.t.t.c.Torrent:   Pieces......: 621 piece(s) (4194304 byte(s)/piece)
[INFO ] 2020-12-27 23:33:08.517 [           main] c.t.t.c.Torrent:   Total size..: 2 601 739 051 byte(s)
[INFO ] 2020-12-27 23:33:08.557 [           main] o.a.j.c.c.JoalConfigProvider: App configuration has been successfully loaded.
[INFO ] 2020-12-27 23:33:13.174 [   annnouncer-1] o.a.j.c.t.c.a.Announcer: /P¬ÈÈVÐATûõÛ%Ú has announced successfully. Response: 1245 seeders, 4 leechers, 1800s interval
[INFO ] 2020-12-27 23:33:19.199 [   annnouncer-0] o.a.j.c.t.c.a.Announcer: À´¾§ñÖ(%ÛKY5:$õq has announced successfully. Response: 1728 seeders, 5 leechers, 1800s interval
[INFO ] 2020-12-27 23:34:08.019 [MessageBroker-1] o.s.w.s.c.WebSocketMessageBrokerStats: WebSocketSession[0 current WS(0)-HttpStream(0)-HttpPoll(0), 0 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(0)-CONNECTED(0)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], outboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], sockJsScheduler[pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]

**Comment by anthonyraymond** [comment]
Bonjour, je pense que le tracker était surchargé, les erreurs que tu me montres indique que le tracker n'a pas pu lire ta requête, probablement car il était dans les choux.

Mais par contre, il ne faut pas t'attendre a voire bouger ton ratio en 30 minutes, remonter le ratio prend du temps, il faut laisse tourner JOAL pendant logtemps
