### ISSUE TITLE
Failure to anounce to tracker

### ISSUE THREAD

**Issue by varaxasthur** [anthonyraymond/joal#118]
Hey, it's me again, sorry if I clog your issue list.
I am using the docker version, here is my config:

```yaml
[...]
joal:
    image: anthonyraymond/joal
    container_name: joal
    restart: unless-stopped
    volumes:
      - "./data/joal/conf:/data"
    ports:
      - MYPORT:MYPORT
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=MYPORT", "--joal.ui.path.prefix=SECRETPREFIX", "--joal.ui.secret-token=SECRETOKEN"]
```

With all the data being replaced ofc.

I often get this in the log:
```
joal                     | [WARN ] 2021-01-19 07:38:28.332 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: %EÖËÉØ±Pºu¢µ has failed to announce
joal                     | com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.                                                                                                       
joal                     |      at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:66)                                                                                              
joal                     |      at org.araymond.joal.core.ttorrent.client.announcer.Announcer.announce(Announcer.java:64)                                                                                                              
joal                     |      at org.araymond.joal.core.ttorrent.client.announcer.request.AnnouncerExecutor.lambda$execute$0(AnnouncerExecutor.java:40)                                                                              
joal                     |      at java.util.concurrent.FutureTask.run(FutureTask.java:266)   
joal                     |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
joal                     |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                                                     
joal                     |      at java.lang.Thread.run(Thread.java:748)                                                                                                                                                               
joal                     | Caused by: com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.
joal                     |      at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:102)
joal                     |      at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:53)
joal                     |      ... 6 more                                                                                                                                                                                             
joal                     | Caused by: org.apache.http.conn.HttpHostConnectException: Connect to XXXX:YYYY [XXXX/ZZ.ZZ.ZZ.ZZ] failed: Connection timed out (Connection timed out)
joal                     |      at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)                                                                                 
joal                     |      at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
joal                     |      at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
joal                     |      at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
joal                     |      at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
joal                     |      at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
joal                     |      at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
joal                     |      at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
joal                     |      at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
joal                     |      at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
joal                     |      at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
joal                     |      at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:98)
joal                     |      ... 7 more
joal                     | Caused by: java.net.ConnectException: Connection timed out (Connection timed out)                                                                                                                           
joal                     |      at java.net.PlainSocketImpl.socketConnect(Native Method)                                                                                                                                               
joal                     |      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)                                                                                                                        
joal                     |      at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)                                                                                                                 
joal                     |      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)                                                                                                                          
joal                     |      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)                                                                                                                                          
joal                     |      at java.net.Socket.connect(Socket.java:589)                                                                                                                                                            
joal                     |      at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)                                         
joal                     |      at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
joal                     |      ... 18 more                                                                                                                                                                                            
joal                     | [WARN ] 2021-01-19 07:38:57.850 [   annnouncer-0] o.a.j.c.t.c.a.Announcer: Ëø{ònïÙ:,ÊÁ&Ù]jê has failed to announce
joal                     | com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.                         
joal                     |      at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:66)                  
joal                     |      at org.araymond.joal.core.ttorrent.client.announcer.Announcer.announce(Announcer.java:64)                  
joal                     |      at org.araymond.joal.core.ttorrent.client.announcer.request.AnnouncerExecutor.lambda$execute$0(AnnouncerExecutor.java:40)                                                                              
joal                     |      at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                                                                            
joal                     |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                                                     
joal                     |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                                                     
joal                     |      at java.lang.Thread.run(Thread.java:748)                                                                                                                                                               
joal                     | Caused by: com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.                                                                                            
joal                     |      at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:102)
joal                     |      at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:53)
joal                     |      ... 6 more                                                                                                                                                                                             
joal                     | Caused by: java.net.SocketTimeoutException: Read timed out                                                                                                                                                  
joal                     |      at java.net.SocketInputStream.socketRead0(Native Method)                                                                                                                                               
joal                     |      at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)                                                                                                                                   
joal                     |      at java.net.SocketInputStream.read(SocketInputStream.java:171)
joal                     |      at java.net.SocketInputStream.read(SocketInputStream.java:141)                    
joal                     |      at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)                                                                                                          
joal                     |      at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)                                                                                                          
joal                     |      at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)                
joal                     |      at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)                                
joal                     |      at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)      
joal                     |      at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)                                                                                                                 
joal                     |      at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)                                                                  
joal                     |      at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)                                                                                                                     
joal                     |      at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)                     
joal                     |      at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)   
joal                     |      at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
joal                     |      at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
joal                     |      at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
joal                     |      at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
joal                     |      at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
joal                     |      at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
joal                     |      at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
joal                     |      at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
joal                     |      at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:98)
joal                     |      ... 7 more
```

I'm not quite sure if joal is working yet as I have not dared to use it for too long but I suppose that failing to announce the results might affect the ratio increase ?

Sometimes I also get:
```
[INFO ] 2021-01-19 07:08:20.375 [   annnouncer-1] o.a.j.c.t.c.a.Announcer: Ëø{ònïÙ:,ÊÁ&Ù]jê has announced successfully.
```
Is there a retry mechanism in place or if the announcement fails, it just flat out fails ?

Thanks again for the project!

**Comment by anthonyraymond** [comment]
Hello :)

`[INFO ] 2021-01-19 07:08:20.375 [   annnouncer-1] o.a.j.c.t.c.a.Announcer: Ëø{ònïÙ:,ÊÁ&Ù]jê has announced successfully.`
is a good think it means your joal instance has reported to the tracker. The cryptic looking text is a torrent unique identifier translated to text (not the most user friendly i agree, it's better in v3 beta already).


`Connection timed out (Connection timed out)` means that joal wanter to announce, but the server did not catch up the request for 30 sec. It could be because the tracker is overwelmed or maybe just a networking error on either side, but it's most likely a overwhelmed server that can't follow up every request he recieve. The timeout (give up) is an HTTP mechanism that prevent a connection being help forever doing nothing, the timeout is adjustable but it's usually around 15-30s.

`Read timed out` is more or less the same as a Connection timeout, in this case it means that the server has accepted the connexion and received our request but it didn't responded in time, so there is nothing to read. That confirm the theory that the tracker can't handle the traffic.

it an announce fails, it does nothing and re-announce in 30 minutes, but if more than (3 or 5 i can't remember) announces fails **in a row** the torrent is removed from joal automatically. The autoremoval is not something we kept in V3, for the future version failing to announce will reset the peer counts at 0 (stop genrating upload on it) and retry to announce in 30 minutes, as soon as it catches up with the tracker joal resume seeding.

**Comment by anthonyraymond** [comment]
@varaxasthur can i close the issue?
