### ISSUE TITLE
Problème avec yggtorrent 

### ISSUE THREAD

**Issue by chicungunya** [anthonyraymond/joal#126]
Salut,

J'ai un problème avec yggtorrent.  Joal ne peut pas atteindre le tracker 5 fois dans un raw ? Qu'est ce que cela veut dire ?

Merci !

**Comment by MathieuGery** [comment]
Salut,
Est-ce que ton compte ygg est bien actif ?

**Comment by chicungunya** [comment]
> Salut,
> Est-ce que ton compte ygg est bien actif ?

Maintenant oui; Mais voici ce que j'obtiens comme erreur maintenant 

```[WARN ] 2021-02-08 22:30:20.383 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: w¾÷ÌIäD8óKÑ has failed to announce,
com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.,
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:66),
	at org.araymond.joal.core.ttorrent.client.announcer.Announcer.announce(Announcer.java:64),
	at org.araymond.joal.core.ttorrent.client.announcer.request.AnnouncerExecutor.lambda$execute$0(AnnouncerExecutor.java:40),
	at java.util.concurrent.FutureTask.run(FutureTask.java:266),
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149),
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624),
	at java.lang.Thread.run(Thread.java:748),
Caused by: com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.,
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:102),
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:53),
	... 6 more,
Caused by: java.net.SocketTimeoutException: Read timed out,
	at java.net.SocketInputStream.socketRead0(Native Method),
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116),
	at java.net.SocketInputStream.read(SocketInputStream.java:171),
	at java.net.SocketInputStream.read(SocketInputStream.java:141),
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137),
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153),
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280),
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138),
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56),
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259),
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163),
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157),
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273),
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125),
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272),
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186),
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89),
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110),
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185),
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83),
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108),
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56),
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:98),
```

**Comment by anthonyraymond** [comment]
L'erreur "Read timed out" signifie que : 
Joal a attendu que le tracker lui réponde, mais le tracker n'a pas fait, au bout de 30 seconde il arrête d'attendre (ce qui est normal).

Il peut y avoir plusieurs raisons:
- 1: Le tracker connait un moment de faiblesse et n'arrive pas a répondre à toutes les requêtes qu'il recoit.
- 2: L'adresse du tracker a peut être changé (ce qui est courant avec YGG), essaye de retelecharger le fichier .torrent depuis le site pour bénéficier du fichier .torrent avec l'adresse du tracker mis à jour.

Mais en général les read timeout c'est plustôt due a une surcharge (cas 1)

**Comment by anthonyraymond** [comment]
En fait j'ai l'impression que les FAI ont commencé a bloquer le domain actuel du tracker (le tracker et pas le site) de YGG.

Du coup il faut au choix:
- Attendre que le tracker change (et il faudra donc retelecharger les .torrent quand cela sera fait)
- Changer les paramètres DNS de ton PC (ipv4 **ET** ipv6) pour prendre par exemple ceux de Google ou CloudFlare. Je te laisse chercher un tuto sur internet il y en a plein. (aprés avoir changer les DNS n'oubli pas de lancer la commande ipconfig /flushdns dans un terminal)

**Comment by chicungunya** [comment]
> En fait j'ai l'impression que les FAI ont commencé a bloquer le domain actuel du tracker (le tracker et pas le site) de YGG.
> 
> Du coup il faut au choix:
> 
>     * Attendre que le tracker change (et il faudra donc retelecharger les .torrent quand ils auront changé le domaine)
> 
>     * Changer les paramètres DNS de ton PC (ipv4 **ET** ipv6) pour prendre par exemple ceux de Google ou CloudFlare. Je te laisse chercher un tuto sur internet il y en a plein. (aprés avoir changer les DNS n'oubli pas de lancer la commande ipconfig /flushdns dans un terminal)

Hello

Merci pour ta reponse. Aujourd'hui ca a fonctionne avec un seul torrent et je n'ai pas eu de probleme au bout de 5 fois 30 minutes donc je vais voir sur le futur, et mes DNS sont deja changés sur mon routeurs. Merci pour le suivi en tout cas !
