### ISSUE TITLE
Cannot fetch IP from https://tnx.nl/ip

### ISSUE THREAD

**Issue by TheSleepySlee** [anthonyraymond/joal#129]
Hi, getting a crash at start. Seems this service no longer working: https://tnx.nl/ip

```
[INFO ] 2021-03-18 19:18:04.054 [           main] o.a.j.JackOfAllTradesApplication: Started JackOfAllTradesApplication in 3.942 seconds (JVM running for 4.875)
[INFO ] 2021-03-18 19:18:04.056 [           main] o.a.j.c.t.c.ConnectionHandler: Listening for incoming peer connections on port 49152.
[INFO ] 2021-03-18 19:18:04.061 [           main] o.a.j.c.t.c.ConnectionHandler: Fetching ip from: https://tnx.nl/ip
[WARN ] 2021-03-18 19:18:05.360 [           main] o.a.j.c.t.c.ConnectionHandler: Failed to fetch Ip from "https://tnx.nl/ip"
java.io.FileNotFoundException: https://tnx.nl/ip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.araymond.joal.core.ttorrent.client.ConnectionHandler.readIpFromProvider(ConnectionHandler.java:81)
	at org.araymond.joal.core.ttorrent.client.ConnectionHandler.tryToFetchFromProviders(ConnectionHandler.java:99)
	at org.araymond.joal.core.ttorrent.client.ConnectionHandler.fetchIp(ConnectionHandler.java:110)
	at org.araymond.joal.core.ttorrent.client.ConnectionHandler.start(ConnectionHandler.java:57)
	at org.araymond.joal.core.SeedManager.init(SeedManager.java:65)
	at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:34)
	at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:17)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:102)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202)
	at org.araymond.joal.JackOfAllTradesApplication.main(JackOfAllTradesApplication.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:86)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by anthonyraymond** [comment]
Thanks for reporting 👍 , i'll remove this one from the list on the next release :)
This error should not prevent JOAL from running properly though, do you have an issue running JOAL?
