### ISSUE TITLE
Compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by Maelep** [anthonyraymond/joal#153]
Current Java: 8.311 (installed today from the official website)

```java
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/araymond/joal/JackOfAllTradesApplication has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

**Comment by ktor-vi** [comment]
Hey ! I solved it by setting the good JAVA_HOME variable in my PATH

**Comment by anthonyraymond** [comment]
You need to update your version of JAVA:

Download the latest LTS version of the JDK here: https://adoptium.net/ 
and during the install choose to set the JAVA_HOME variable when asked for what component to install
