### ISSUE TITLE
Error for all authkey tracker

### ISSUE THREAD

**Issue by bingyu50** [anthonyraymond/joal#171]
got below error for this kind of tracker: https://aaa.bbb.cccc/announce.php?authkey=9207|885|AJ2uIk80]

"TORRENT WAS REJECTED BY SERVER: JAVA.NET.URISYNTAXEXCEPTION: ILLEGAL CHARACTER IN QUERY AT INDEX 48:  https://aaa.bbb.cccc/announce.php?authkey=9207|885|AJ2uIk80]"

**Comment by bingyu50** [comment]
<img width="226" alt="image" src="https://user-images.githubusercontent.com/15845429/189464761-c2b8ec81-4554-407e-9865-58d1b7879720.png">

**Comment by laur89** [comment]
@anthonyraymond is this likely thrown from `com.turn.ttorrent.common.Torrent`, possibly line #176 (`URI uri = new URI(tracker.getString());`)?

**Comment by google2013** [comment]
> @anthonyraymond is this likely thrown from `com.turn.ttorrent.common.Torrent`, possibly line [#176](https://github.com/mpetazzoni/ttorrent/blob/ttorrent-1.5/core/src/main/java/com/turn/ttorrent/common/Torrent.java#L176) (`URI uri = new URI(tracker.getString());`)? Sounds like they should encode the uri before feeding it to URI constructor.

Is there any pull requests? Thank you very much ！

**Comment by laur89** [comment]
No PRs. What needs be done:
a) verify it's solved in turn.ttorrent project's upstream
b) upgrade joal to use latest version of ttorrent (currently used version is quite a bit behind)

I _might_ take it on, but only if/when #172 is merged.

**Comment by cwyalpha** [comment]
Caused by: java.net.URISyntaxException: Illegal character in query at index 53: https://xxx/announce.php?authkey=12345|67890|abcxyz
        at java.base/java.net.URI$Parser.fail(URI.java:2973)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3144)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3232)
        at java.base/java.net.URI$Parser.parse(URI.java:3174)
        at java.base/java.net.URI.<init>(URI.java:623)
        at com.turn.ttorrent.common.Torrent.<init>(Torrent.java:191)
        ... 8 more

I have the same issue, but an earlier version of joal is OK for this site

**Comment by anthonyraymond** [comment]
Hello there, i'm aware of this issue, but i'm having a lot of work atm and i don't have much time to look at it to eventually fix the issue on my spare time.

But i will as soon as possible. I'll keep you updated

**Comment by HmgvPy4Q** [comment]
Temporary solution: encode '|' to '%7C' (edit the tracker url in the torrent file).

**Comment by anthonyraymond** [comment]
Note to me:
Should be possible to update to latest version of ttorent and replace parsing with : com/turn/ttorrent/common/TorrentParser.java

Joal is using an old version, but i don't think that it'm depending of ttorrent too much except for some constants or parsing.

Maybe @laur89 will happen to have some time before i do ^^.

Place your bets.

**Comment by butts136** [comment]
Hi, Any news about this problem ? Editing ('|' to '%7C') the trackers is not that easy when you download a couple torrents a day.

Just asking, Thanks ;)

**Comment by laur89** [comment]
@butts136 been away from joal for a while. Will try to make some time coming week, but no promises.

**Comment by skywalkerscott** [comment]
> @butts136 been away from joal for a while. Will try to make some time coming week, but no promises.

Are there any other tools similar to JOAL? The authkey problem is still there.
