### ISSUE TITLE
Error managing large amount of torrents.

### ISSUE THREAD

**Issue by tiritibambix** [anthonyraymond/joal#179]
I have 300+ torrents that I'd like to load in joal.
Fixed the limit to 500.

Apparently, is generates an error.
I'm not sure the reason why. Is it because of the number ? Of a tracker ?  Of a specific torrent ?
Running as a docker container

Here's the log related to that error:

```
[ERROR] 2022-11-30 22:05:09.769 [           main] o.a.j.ApplicationReadyListener: Fatal error encountered

java.lang.IllegalStateException: Fatal error encountered

	at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:35)

	at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:16)

	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)

	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)

	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)

	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)

	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)

	at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:114)

	at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82)

	at java.base/java.util.ArrayList.forEach(Unknown Source)

	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)

	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)

	at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:82)

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323)

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)

	at org.araymond.joal.JackOfAllTradesApplication.main(JackOfAllTradesApplication.java:15)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)

	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)

	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)

	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!

	at java.base/java.util.TimSort.mergeLo(Unknown Source)

	at java.base/java.util.TimSort.mergeAt(Unknown Source)

	at java.base/java.util.TimSort.mergeCollapse(Unknown Source)

	at java.base/java.util.TimSort.sort(Unknown Source)

	at java.base/java.util.Arrays.sort(Unknown Source)

	at java.base/java.util.ArrayList.sort(Unknown Source)

	at java.base/java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)

	at java.base/java.util.stream.Sink$ChainedReference.end(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)

	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)

	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)

	at java.base/java.util.stream.ReferencePipeline.findAny(Unknown Source)

	at org.araymond.joal.core.torrent.watcher.TorrentFileProvider.getTorrentNotIn(TorrentFileProvider.java:124)

	at org.araymond.joal.core.ttorrent.client.Client.addTorrent(Client.java:102)

	at org.araymond.joal.core.ttorrent.client.Client.start(Client.java:87)

	at org.araymond.joal.core.SeedManager.startSeeding(SeedManager.java:128)

	at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:33)

... 24 more
```

**Comment by anthonyraymond** [comment]
This is most likely related to https://github.com/anthonyraymond/joal-desktop/issues/89
I'm looking into it. Thanks for providing the log

**Comment by tiritibambix** [comment]
> I'm looking into it.
Awesome.

In the meantime, I tried loading joal with only 3 torrents and add others 50 by 50 and giving it time to swallow them.
For now, it is running with 331 torrents.

**Comment by anthonyraymond** [comment]
I found the reason why it's crashing, i'm publishing a fix

**Comment by anthonyraymond** [comment]
Version *2.1.33* has been release to address the issue: https://github.com/anthonyraymond/joal/releases

**Comment by tiritibambix** [comment]
Awesome, thank you.
