### ISSUE TITLE
Impossible to add torrents

### ISSUE THREAD

**Issue by tdm-fr** [anthonyraymond/joal#200]
Hello,

Joal runned perfectly for a few weeks but stopped working.
After a few tries I deleted everything in my docker and started from scratch : I still have the issue.

When adding a torrent, Joal tries to "initiate" (I think) the connection and during 10 seconds there are only interrogation marks for seeders, leechers and B/s.
Then after this 10 seconds the torrents disappear on the UI.
It is put in the "archived" folder.

![image](https://user-images.githubusercontent.com/3950014/226321948-1728e2c7-af9c-43f8-9a70-33d4c07a6481.png)

I don't know what I am doing wrong, especially since it stopped working without any reason (no change to report on my part).

Have you ever encountered this issue ? Do you need more information from me to be able to troubleshoot ?

Regards,
tdm-fr

**Comment by tdm-fr** [comment]
Actually it might be the website that is blocking this. I tried an ubuntu torrent and it's working fine.

Here are the logs from docker:
`[WARN ] 2023-03-20 16:00:44.997 [   annnouncer-1] o.a.j.c.t.c.a.Announcer: $KCSÈÿÏÃ/bÅ£ í¡ has failed to announce

com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.

	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:59)

	at org.araymond.joal.core.ttorrent.client.announcer.Announcer.announce(Announcer.java:66)

	at org.araymond.joal.core.ttorrent.client.announcer.request.AnnouncerExecutor.lambda$execute$0(AnnouncerExecutor.java:39)

	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.base/java.lang.Thread.run(Unknown Source)

Caused by: com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.

	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:94)

	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:46)

	... 6 more

Caused by: org.apache.http.conn.HttpHostConnectException: Connect to serv.supertracker.org:8080 [serv.supertracker.org/127.0.0.1] failed: Connection refused (Connection refused)

	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)

	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)

	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)

	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)

	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)

	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)

	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)

	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)

	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)

	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)

	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)

	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:90)

	... 7 more

Caused by: java.net.ConnectException: Connection refused (Connection refused)

	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)

	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)

	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)

	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)

	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)

	at java.base/java.net.Socket.connect(Unknown Source)

	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)

	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)

`

**Comment by tdm-fr** [comment]
Ok found the solution, or at least the reason.
**If I choose a torrent around one years old it works. If the torrent is older (3, 4, 5 years, ...) it doesn't work.**
I don't know why because no matter the age of the torrent it's downloading in a bittorrent client, it's only Joal who seems to have an issue.

**Comment by tdm-fr** [comment]
Thanks for you answers ! In any case I managed to work with it for the moment :)
