### ISSUE TITLE
Can't acces UI listener fail 

### ISSUE THREAD

**Issue by ext4e** [anthonyraymond/joal#219]
Hello everyone, 

Sorry but i cant fuigure what's wrong in my configuration.

I tried to setup joal with docker :

```
version: "2.4"
services:
  joal:
    image: anthonyraymond/joal
    container_name: joal
    network_mode: CustomBridge
    environment:
      - PUID=1026
      - PGID=100
    volumes:
      - /volume1/docker/joal/ressources/:/data
    ports:
      - '6543:6543'   
    command:
      --joal-conf=/data
      --spring.main.web-environment=true
      --server.port="6543"
      --joal.ui.path.prefix=xxxxxxx
      --joal.ui.secret-token=xxxxxxxxxx      
    restart: unless-stopped
 ```
    
    but keep geting errors :

```    
    [INFO ] 2023-10-23 09:57:49.670 [           main] o.a.j.JackOfAllTradesApplication: Starting JackOfAllTradesApplication v2.1.34 using Java 11.0.13 on 54cf53a08e1b with PID 1 (/joal/joal.jar started by root in /joal)
[INFO ] 2023-10-23 09:57:49.684 [           main] o.a.j.JackOfAllTradesApplication: No active profile set, falling back to 1 default profile: "default"
[INFO ] 2023-10-23 09:57:52.356 [           main] o.s.b.w.e.t.TomcatWebServer: Tomcat initialized with port(s): 6543 (http)
[INFO ] 2023-10-23 09:57:52.390 [           main] o.a.c.h.Http11NioProtocol: Initializing ProtocolHandler ["http-nio-6543"]
[INFO ] 2023-10-23 09:57:52.391 [           main] o.a.c.c.StandardService: Starting service [Tomcat]
[INFO ] 2023-10-23 09:57:52.392 [           main] o.a.c.c.StandardEngine: Starting Servlet engine: [Apache Tomcat/9.0.65]
[INFO ] 2023-10-23 09:57:52.813 [           main] o.a.c.c.C.[.[.[/]: Initializing Spring embedded WebApplicationContext
[INFO ] 2023-10-23 09:57:52.813 [           main] o.s.b.w.s.c.ServletWebServerApplicationContext: Root WebApplicationContext: initialization completed in 3021 ms
[INFO ] 2023-10-23 09:57:55.283 [           main] o.s.s.w.DefaultSecurityFilterChain: Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@4aac85fa, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@21fff664, org.springframework.security.web.context.SecurityContextPersistenceFilter@2f879bab, org.springframework.security.web.header.HeaderWriterFilter@6f099cef, org.springframework.security.web.csrf.CsrfFilter@5d39f2d8, org.springframework.security.web.authentication.logout.LogoutFilter@18a645fd, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@46c00568, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@56ccd751, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@6079cf5, org.springframework.security.web.session.SessionManagementFilter@4bff2185, org.springframework.security.web.access.ExceptionTranslationFilter@1dab9dd6, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@2fe88a09]
[INFO ] 2023-10-23 09:57:55.486 [           main] o.s.b.a.w.s.WelcomePageHandlerMapping: Adding welcome page: class path resource [public/index.html]
[INFO ] 2023-10-23 09:57:55.724 [           main] o.a.c.h.Http11NioProtocol: Starting ProtocolHandler ["http-nio-6543"]
[INFO ] 2023-10-23 09:57:55.982 [           main] o.s.b.w.e.t.TomcatWebServer: Tomcat started on port(s): 6543 (http) with context path ''
[INFO ] 2023-10-23 09:57:55.986 [           main] o.s.m.s.b.SimpleBrokerMessageHandler: Starting...
[INFO ] 2023-10-23 09:57:55.987 [           main] o.s.m.s.b.SimpleBrokerMessageHandler: BrokerAvailabilityEvent[available=true, SimpleBrokerMessageHandler [org.springframework.messaging.simp.broker.DefaultSubscriptionRegistry@1948ea69]]
[INFO ] 2023-10-23 09:57:55.988 [           main] o.s.m.s.b.SimpleBrokerMessageHandler: Started.
[INFO ] 2023-10-23 09:57:56.004 [           main] o.a.j.JackOfAllTradesApplication: Started JackOfAllTradesApplication in 7.119 seconds (JVM running for 9.716)
[INFO ] 2023-10-23 09:57:56.013 [           main] o.a.j.c.t.c.ConnectionHandler: Listening for incoming peer connections on port 49152
[INFO ] 2023-10-23 09:57:56.013 [           main] o.a.j.c.t.c.ConnectionHandler: Fetching ip from http://whatismyip.akamai.com
[INFO ] 2023-10-23 09:57:56.401 [           main] o.a.j.c.t.c.ConnectionHandler: Successfully fetched public IP address: [82.65.24.97]
[INFO ] 2023-10-23 09:57:56.401 [           main] o.a.j.c.t.c.ConnectionHandler: IP reported to tracker will be: 82.65.24.97
[INFO ] 2023-10-23 09:57:56.569 [           main] o.a.j.c.c.JoalConfigProvider: App configuration has been successfully loaded
[ERROR] 2023-10-23 09:57:56.637 [           main] o.a.j.ApplicationReadyListener: Fatal error encountered
java.lang.IllegalStateException: Fatal error encountered
	at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:35)
	at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:16)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:82)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.araymond.joal.JackOfAllTradesApplication.main(JackOfAllTradesApplication.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.io.FileNotFoundException: BitTorrent client configuration file [/data/clients/qbittorrent-3.3.16.client] not found
	at org.araymond.joal.core.client.emulated.BitTorrentClientProvider.generateNewClient(BitTorrentClientProvider.java:75)
	at org.araymond.joal.core.SeedManager.startSeeding(SeedManager.java:123)
	at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:33)
      
	... 24 more
[INFO ] 2023-10-23 09:57:56.641 [           main] o.a.j.ApplicationClosingListener: Gracefully shutting down application...
[INFO ] 2023-10-23 09:57:56.642 [       Thread-1] o.a.j.c.t.c.ConnectionHandler: IP fetcher thread has been stopped
[INFO ] 2023-10-23 09:57:56.648 [           main] o.a.j.ApplicationClosingListener: JOAL gracefully shut down
[INFO ] 2023-10-23 09:57:56.694 [           main] o.a.c.h.Http11NioProtocol: Pausing ProtocolHandler ["http-nio-6543"]
[INFO ] 2023-10-23 09:57:56.695 [           main] o.a.c.c.StandardService: Stopping service [Tomcat]
[INFO ] 2023-10-23 09:57:56.705 [           main] o.a.c.h.Http11NioProtocol: Stopping ProtocolHandler ["http-nio-6543"]
[INFO ] 2023-10-23 09:57:56.709 [           main] o.a.c.h.Http11NioProtocol: Destroying ProtocolHandler ["http-nio-6543"]
```
    
    Anyone know what could be the problem ?
    
    thanks a lot

**Comment by anthonyraymond** [comment]
The error message says : *BitTorrent client configuration file [/data/clients/qbittorrent-3.3.16.client]*

Which means that the volume you are mounting does not contains a folder with the client qbittorrent-3.3.16.

To resolve this: copy **ALL** the content of the resources folder from: **https://github.com/anthonyraymond/joal/** into your folder: **/volume1/docker/joal/ressources**.

Then restart joal and you should be good 😃

**Comment by ext4e** [comment]
Thank you a lot it works like a charm now :)
