### ISSUE TITLE
Docker container exit with 

### ISSUE THREAD

**Issue by ksad** [anthonyraymond/joal#235]
Hi
I'm trying to run joal inside a docker container using the below command
```
docker run -d \
    -p 9000:9000 \
    --name="joal" \
    anthonyraymond/joal:latest \
    --joal-conf\="/data" \
    --spring.main.web-environment\=true \
    --server.port\="9000" \
    --joal.ui.path.prefix\="joal" \
    --joal.ui.secret-token\="04500796"
```
but the container wont start and exit with the following error :
```
[INFO ] 2024-05-19 00:09:50.282 [           main] o.a.j.JackOfAllTradesApplication: Starting JackOfAllTradesApplication v2.1.36 using Java 11.0.13 on 7464ad481776 with PID 1 (/joal/joal.jar started by root in /joal)
[INFO ] 2024-05-19 00:09:50.287 [           main] o.a.j.JackOfAllTradesApplication: No active profile set, falling back to 1 default profile: "default"
[INFO ] 2024-05-19 00:09:51.106 [           main] o.s.b.w.e.t.TomcatWebServer: Tomcat initialized with port(s): 9000 (http)
[INFO ] 2024-05-19 00:09:51.122 [           main] o.a.c.h.Http11NioProtocol: Initializing ProtocolHandler ["http-nio-9000"]
[INFO ] 2024-05-19 00:09:51.122 [           main] o.a.c.c.StandardService: Starting service [Tomcat]
[INFO ] 2024-05-19 00:09:51.122 [           main] o.a.c.c.StandardEngine: Starting Servlet engine: [Apache Tomcat/9.0.65]
[INFO ] 2024-05-19 00:09:51.178 [           main] o.a.c.c.C.[.[.[/]: Initializing Spring embedded WebApplicationContext
[INFO ] 2024-05-19 00:09:51.178 [           main] o.s.b.w.s.c.ServletWebServerApplicationContext: Root WebApplicationContext: initialization completed in 856 ms
[WARN ] 2024-05-19 00:09:51.275 [           main] o.a.j.c.SeedManager: Sub-folder 'torrents' is missing in joal conf folder: [/data/torrents]
[WARN ] 2024-05-19 00:09:51.275 [           main] o.a.j.c.SeedManager: Sub-folder 'clients' is missing in joal conf folder: [/data/clients]
[ERROR] 2024-05-19 00:09:51.277 [           main] o.a.j.c.t.w.TorrentFileProvider: Folder [/data/torrents] does not exist
[WARN ] 2024-05-19 00:09:51.278 [           main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationClosingListener' defined in URL [jar:file:/joal/joal.jar!/BOOT-INF/classes!/org/araymond/joal/ApplicationClosingListener.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'seedManager' defined in class path resource [org/araymond/joal/web/config/BeanConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.araymond.joal.core.SeedManager]: Factory method 'seedManager' threw exception; nested exception is java.io.FileNotFoundException: Torrent folder [/data/torrents] not found
[INFO ] 2024-05-19 00:09:51.280 [           main] o.a.c.c.StandardService: Stopping service [Tomcat]
[INFO ] 2024-05-19 00:09:51.289 [           main] o.s.b.a.l.ConditionEvaluationReportLoggingListener: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ERROR] 2024-05-19 00:09:51.303 [           main] o.s.b.SpringApplication: Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationClosingListener' defined in URL [jar:file:/joal/joal.jar!/BOOT-INF/classes!/org/araymond/joal/ApplicationClosingListener.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'seedManager' defined in class path resource [org/araymond/joal/web/config/BeanConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.araymond.joal.core.SeedManager]: Factory method 'seedManager' threw exception; nested exception is java.io.FileNotFoundException: Torrent folder [/data/torrents] not found
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.araymond.joal.JackOfAllTradesApplication.main(JackOfAllTradesApplication.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'seedManager' defined in class path resource [org/araymond/joal/web/config/BeanConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.araymond.joal.core.SeedManager]: Factory method 'seedManager' threw exception; nested exception is java.io.FileNotFoundException: Torrent folder [/data/torrents] not found
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 27 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.araymond.joal.core.SeedManager]: Factory method 'seedManager' threw exception; nested exception is java.io.FileNotFoundException: Torrent folder [/data/torrents] not found
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 41 more
Caused by: java.io.FileNotFoundException: Torrent folder [/data/torrents] not found
	at org.araymond.joal.core.torrent.watcher.TorrentFileProvider.<init>(TorrentFileProvider.java:53)
	at org.araymond.joal.core.SeedManager.<init>(SeedManager.java:72)
	at org.araymond.joal.web.config.BeanConfig.seedManager(BeanConfig.java:21)
	at org.araymond.joal.web.config.BeanConfig$$EnhancerBySpringCGLIB$$67698135.CGLIB$seedManager$0(<generated>)
	at org.araymond.joal.web.config.BeanConfig$$EnhancerBySpringCGLIB$$67698135$$FastClassBySpringCGLIB$$c2b3c42f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.araymond.joal.web.config.BeanConfig$$EnhancerBySpringCGLIB$$67698135.seedManager(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 42 more
```

**Comment by gui-lau** [comment]
Hi,
I'm using the Java standalone version of Joal since ages and it's still working like a charm (running over an AWS EC2).
Now, I'm trying to run the Docker version, but it keeps failling with the same error as above.
In my case, the /data/torrents and /data/clients exist 👍 

Please find below :

`[root@ip-172-16-30-121 ~]# docker run -d --name="joal" anthonyraymond/joal --joal-conf="/data" --spring.main.web-environment=true --server.port="8081" --joal.ui.path.prefix="SECRET_OBFUSCATION_PATH" --joal.ui.secret-token="SECRET_TOKEN"`

`[root@ip-172-16-30-121 /]# find /data -type d -ls
 10459807      0 drwxrwxrwx   4 root     root           37 Aug 31 21:31 /data
  1431627      0 drwxrwxrwx   2 root     root            6 Aug 31 21:31 /data/torrents
 10459817      0 drwxrwxrwx   2 root     root            6 Aug 31 21:31 /data/clients`

Any help would be appreciated !
