### ISSUE TITLE
Fatal Error: No valid http trackers provided

### ISSUE THREAD

**Issue by meyverick** [anthonyraymond/joal#239]
How to fix this error? I don't understand what's going wrong?

# Folder Structure
```
containers/joal/
    clients/(69.client)
    torrents/(50+.torrent)
    config.json
```

# Config.json
```json
{
  "minUploadRate": 5120,
  "maxUploadRate": 20480,
  "simultaneousSeed": 200,
  "client": "utorrent-3.5.0_43916.client",
  "keepTorrentWithZeroLeechers": false,
  "uploadRatioTarget": -1.0
}
```

# docker-compose.yml
```yml
volume:
    joal:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: 'C:\*****\containers\joal'
services:
    joal:
        container_name: joal
        image: anthonyraymond/joal:latest
        restart: always
        networks:
            plework:
                ipv4_address: *****
        ports:
            - "8113:8113/tcp"
        environment:
            PUID: 1000
            PGID: 1000
        command: ["--joal-conf=/config", "--spring.main.web-environment=false", "--server.port=8113", "--joal.ui.path.prefix=joal", "--joal.ui.secret-token=*****"]
        volumes:
            - joal:/config
```

# Logs
```
2024-07-21 06:54:56 [INFO ] 2024-07-21 04:54:56.084 [           main] o.a.j.c.c.JoalConfigProvider: App configuration has been successfully loaded
2024-07-21 06:54:56 [ERROR] 2024-07-21 04:54:56.227 [           main] o.a.j.ApplicationReadyListener: Fatal error encountered
2024-07-21 06:54:56 java.lang.IllegalStateException: Fatal error encountered
2024-07-21 06:54:56     at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:35)
2024-07-21 06:54:56     at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:16)
2024-07-21 06:54:56     at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
2024-07-21 06:54:56     at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
2024-07-21 06:54:56     at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
2024-07-21 06:54:56     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
2024-07-21 06:54:56     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
2024-07-21 06:54:56     at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:114)
2024-07-21 06:54:56     at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82)
2024-07-21 06:54:56     at java.base/java.util.ArrayList.forEach(Unknown Source)
2024-07-21 06:54:56     at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
2024-07-21 06:54:56     at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
2024-07-21 06:54:56     at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:82)
2024-07-21 06:54:56     at org.springframework.boot.SpringApplication.run(SpringApplication.java:323)
2024-07-21 06:54:56     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
2024-07-21 06:54:56     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
2024-07-21 06:54:56     at org.araymond.joal.JackOfAllTradesApplication.main(JackOfAllTradesApplication.java:15)
2024-07-21 06:54:56     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-07-21 06:54:56     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2024-07-21 06:54:56     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2024-07-21 06:54:56     at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2024-07-21 06:54:56     at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
2024-07-21 06:54:56     at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
2024-07-21 06:54:56     at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
2024-07-21 06:54:56     at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
2024-07-21 06:54:56 Caused by: org.araymond.joal.core.ttorrent.client.announcer.tracker.NoMoreUriAvailableException: No valid http trackers provided
2024-07-21 06:54:56     at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClientUriProvider.<init>(TrackerClientUriProvider.java:23)
2024-07-21 06:54:56     at org.araymond.joal.core.ttorrent.client.announcer.Announcer.buildTrackerClient(Announcer.java:53)
2024-07-21 06:54:56     at org.araymond.joal.core.ttorrent.client.announcer.Announcer.<init>(Announcer.java:43)
2024-07-21 06:54:56     at org.araymond.joal.core.ttorrent.client.announcer.AnnouncerFactory.create(AnnouncerFactory.java:16)
2024-07-21 06:54:56     at org.araymond.joal.core.ttorrent.client.Client.addTorrent(Client.java:130)
2024-07-21 06:54:56     at org.araymond.joal.core.ttorrent.client.Client.addTorrentFromDirectory(Client.java:126)
2024-07-21 06:54:56     at org.araymond.joal.core.ttorrent.client.Client.start(Client.java:102)
2024-07-21 06:54:56     at org.araymond.joal.core.SeedManager.startSeeding(SeedManager.java:140)
2024-07-21 06:54:56     at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:33)
2024-07-21 06:54:56     ... 24 more
2024-07-21 06:54:56 [INFO ] 2024-07-21 04:54:56.230 [           main] o.a.j.ApplicationClosingListener: Gracefully shutting down application...
2024-07-21 06:54:56 [INFO ] 2024-07-21 04:54:56.235 [       Thread-1] o.a.j.c.t.c.ConnectionHandler: IP fetcher thread has been stopped
2024-07-21 06:54:56 [INFO ] 2024-07-21 04:54:56.235 [           main] o.a.j.ApplicationClosingListener: JOAL gracefully shut down
```

**Comment by WoisWoi** [comment]
I'm having the same issue, I had no problem before.

**Comment by WoisWoi** [comment]
Why setting this to false : --spring.main.web-environment=false ?

**Comment by Banzai262** [comment]
Have you found a fix? I am getting this same error after a restart

**Comment by nigerninja** [comment]
Same here, i'm currently seeing the same issue after a restart, please advise

**Comment by pseudomix** [comment]
Hi,
I have the same error. AnyOne have figured out where is the issue ?
Cheers

**Comment by Victor333Huesca** [comment]
From my understanding of the code, it occurs when none of the tracker URLs are on the `http` protocol.
You can see in the code here:
https://github.com/anthonyraymond/joal/blob/cad5df11990d4304476d574484003ccbcdd0b700/src/main/java/org/araymond/joal/core/ttorrent/client/announcer/tracker/TrackerClientUriProvider.java#L17-L24

The quickest way I came up with to find the culprit `.torrent` file is with `grep -B2 ' [0-9]\. [^h]' my_joal_log.log` 
This will show all torrents that at least one non-http protocol.

You can then remove those where all trackers are on non-http URLs.
