### ISSUE TITLE
Issue with Joal v2.1.4 + openSUSE Leap + openjdk version "1.8.0_171"

### ISSUE THREAD

**Issue by MDVAurelien** [anthonyraymond/joal#37]
Hi, i have this error with Joal v2.1.4 + openSUSE Leap 15.0 + openjdk version "1.8.0_171".

Thank you very much for your excellent work!

[0m[INFO ] 2018-07-24 22:55:15.747 [           main] o.a.j.JackOfAllTradesApplication: Starting JackOfAllTradesApplication v2.1.4 on r2d2 with PID 18455 (/opt/joal-master/jack-of-all-trades-2.1.4.jar started by sysop in /opt/joal-master)
[m[0m[INFO ] 2018-07-24 22:55:15.754 [           main] o.a.j.JackOfAllTradesApplication: No active profile set, falling back to default profiles: default
[m[0m[INFO ] 2018-07-24 22:55:15.829 [           main] o.s.c.a.AnnotationConfigApplicationContext: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@59a6e353: startup date [Tue Jul 24 22:55:15 CEST 2018]; root of context hierarchy
[m[0m[INFO ] 2018-07-24 22:55:16.797 [           main] o.s.b.f.a.AutowiredAnnotationBeanPostProcessor: JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
[m[0m[INFO ] 2018-07-24 22:55:17.111 [           main] o.s.s.c.ThreadPoolTaskExecutor: Initializing ExecutorService  'taskExecutor'
[m[0m[INFO ] 2018-07-24 22:55:17.422 [           main] o.a.j.JackOfAllTradesApplication: Started JackOfAllTradesApplication in 2.255 seconds (JVM running for 3.413)
[m[0;33m[WARN ] 2018-07-24 22:55:17.432 [           main] o.a.j.c.t.c.ConnectionHandler: Could not bind to r2d2/192.168.1.54:49152, trying next port...
[m[0;33m[WARN ] 2018-07-24 22:55:17.433 [           main] o.a.j.c.t.c.ConnectionHandler: Could not bind to r2d2/192.168.1.54:49153, trying next port...
[m[0;33m[WARN ] 2018-07-24 22:55:17.433 [           main] o.a.j.c.t.c.ConnectionHandler: Could not bind to r2d2/192.168.1.54:49154, trying next port...
[m[0;33m[WARN ] 2018-07-24 22:55:17.433 [           main] o.a.j.c.t.c.ConnectionHandler: Could not bind to r2d2/192.168.1.54:49155, trying next port...
[m[0;33m[WARN ] 2018-07-24 22:55:17.433 [           main] o.a.j.c.t.c.ConnectionHandler: Could not bind to r2d2/192.168.1.54:49156, trying next port...
[m[0;33m[WARN ] 2018-07-24 22:55:17.434 [           main] o.a.j.c.t.c.ConnectionHandler: Could not bind to r2d2/192.168.1.54:49157, trying next port...

....
[m[31m[ERROR] 2018-07-24 22:55:18.523 [           main] o.a.j.ApplicationReadyListener: Fatal error encountered
java.lang.IllegalStateException: Fatal error encountered
	at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:37)
	at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:17)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:103)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at org.araymond.joal.JackOfAllTradesApplication.main(JackOfAllTradesApplication.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.io.IOException: No available port for the BitTorrent client!
	at org.araymond.joal.core.ttorrent.client.ConnectionHandler.bindToPort(ConnectionHandler.java:148)
	at org.araymond.joal.core.ttorrent.client.ConnectionHandler.start(ConnectionHandler.java:53)
	at org.araymond.joal.core.SeedManager.init(SeedManager.java:60)
	at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:34)
	... 20 more
[m[0m[INFO ] 2018-07-24 22:55:18.525 [           main] o.s.c.a.AnnotationConfigApplicationContext: Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@59a6e353: startup date [Tue Jul 24 22:55:15 CEST 2018]; root of context hierarchy
[m[0m[INFO ] 2018-07-24 22:55:18.526 [           main] o.a.j.ApplicationClosingListener: Gracefully shutting down application.
[m[0m[INFO ] 2018-07-24 22:55:18.526 [           main] o.a.j.ApplicationClosingListener: JOAL gracefully shut down.
[m

**Comment by anthonyraymond** [comment]
Hi, for some reasons, joal can find a port available for listening (you can see it in the log : `Could not bind to r2d2/192.168.1.54:XXXX`
And after testing all ports in the given interval, it results in `No available port for the BitTorrent client!`.

I've just published a new version (2.1.5) which makes joal more verbose about what failed in binding the port.
Can you download and run the new version, then paste the new log here as well please? :)

**Comment by MDVAurelien** [comment]
Seriously a big thank you for your incredible speed !!! it works perfectly with this new version, strange!

**Comment by anthonyraymond** [comment]
That's weird indeed. I did changed a line of code, but since i'm starting a SocketSetver the address isn't suposed to change anything to the process.

But... :smile: 

Have fun :)
