### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by antoyo** [anthonyraymond/joal#55]
Hi.
I've tried joal with the transmission client, but it does not seem to work.
I get the following log:
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[INFO ] 2019-01-19 10:29:06.709 [           main] o.a.j.JackOfAllTradesApplication: Starting JackOfAllTradesApplication v2.1.11 on laptop with PID 6899 (/tmp/joal/jack-of-all-trades-2.1.11.jar started by user in /tmp/joal)
[INFO ] 2019-01-19 10:29:06.717 [           main] o.a.j.JackOfAllTradesApplication: No active profile set, falling back to default profiles: default
[INFO ] 2019-01-19 10:29:08.494 [           main] o.s.b.w.e.t.TomcatWebServer: Tomcat initialized with port(s): 41669 (http)
[INFO ] 2019-01-19 10:29:08.537 [           main] o.a.c.h.Http11NioProtocol: Initializing ProtocolHandler ["http-nio-41669"]
[INFO ] 2019-01-19 10:29:08.552 [           main] o.a.c.c.StandardService: Starting service [Tomcat]
[INFO ] 2019-01-19 10:29:08.554 [           main] o.a.c.c.StandardEngine: Starting Servlet Engine: Apache Tomcat/9.0.12
[INFO ] 2019-01-19 10:29:08.574 [           main] o.a.c.c.AprLifecycleListener: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
[INFO ] 2019-01-19 10:29:08.699 [           main] o.a.c.c.C.[.[.[/]: Initializing Spring embedded WebApplicationContext
[INFO ] 2019-01-19 10:29:08.700 [           main] o.s.w.c.ContextLoader: Root WebApplicationContext: initialization completed in 1907 ms
[INFO ] 2019-01-19 10:29:08.799 [           main] o.s.b.w.s.FilterRegistrationBean: Mapping filter: 'characterEncodingFilter' to: [/*]
[INFO ] 2019-01-19 10:29:08.799 [           main] o.s.b.w.s.FilterRegistrationBean: Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
[INFO ] 2019-01-19 10:29:08.799 [           main] o.s.b.w.s.FilterRegistrationBean: Mapping filter: 'formContentFilter' to: [/*]
[INFO ] 2019-01-19 10:29:08.799 [           main] o.s.b.w.s.FilterRegistrationBean: Mapping filter: 'requestContextFilter' to: [/*]
[INFO ] 2019-01-19 10:29:08.800 [           main] o.s.b.w.s.DelegatingFilterProxyRegistrationBean: Mapping filter: 'springSecurityFilterChain' to: [/*]
[INFO ] 2019-01-19 10:29:08.987 [           main] o.s.s.c.ThreadPoolTaskExecutor: Initializing ExecutorService 'taskExecutor'
[INFO ] 2019-01-19 10:29:09.342 [           main] o.s.b.a.w.s.WelcomePageHandlerMapping: Adding welcome page: class path resource [public/index.html]
[INFO ] 2019-01-19 10:29:09.569 [           main] o.s.b.a.s.s.UserDetailsServiceAutoConfiguration: 

Using generated security password: <HIDDEN>

[INFO ] 2019-01-19 10:29:09.759 [           main] o.s.s.w.DefaultSecurityFilterChain: Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@1a1ed4e5, org.springframework.security.web.context.SecurityContextPersistenceFilter@4dd94a58, org.springframework.security.web.header.HeaderWriterFilter@30b9eadd, org.springframework.security.web.csrf.CsrfFilter@4ee33af7, org.springframework.security.web.authentication.logout.LogoutFilter@39aa45a1, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@54534abf, org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter@2c42b421, org.springframework.security.web.authentication.ui.DefaultLogoutPageGeneratingFilter@667e34b1, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@45673f68, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@a8a8b75, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@2e647e59, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@1c6e0a08, org.springframework.security.web.session.SessionManagementFilter@412c995d, org.springframework.security.web.access.ExceptionTranslationFilter@6b9c69a9, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@4564e94b]
[INFO ] 2019-01-19 10:29:09.839 [           main] o.a.c.h.Http11NioProtocol: Starting ProtocolHandler ["http-nio-41669"]
[INFO ] 2019-01-19 10:29:09.849 [           main] o.a.t.u.n.NioSelectorPool: Using a shared selector for servlet write/read
[INFO ] 2019-01-19 10:29:09.880 [           main] o.s.b.w.e.t.TomcatWebServer: Tomcat started on port(s): 41669 (http) with context path ''
[INFO ] 2019-01-19 10:29:09.885 [           main] o.a.j.JackOfAllTradesApplication: Started JackOfAllTradesApplication in 3.809 seconds (JVM running for 5.031)
[INFO ] 2019-01-19 10:29:09.889 [           main] o.a.j.c.t.c.ConnectionHandler: Listening for incoming peer connections on port 49152.
[INFO ] 2019-01-19 10:29:09.894 [           main] o.a.j.c.t.c.ConnectionHandler: Fetching ip from: http://icanhazip.com/
[INFO ] 2019-01-19 10:29:10.004 [           main] o.a.j.c.t.c.ConnectionHandler: Successfully fetch public IP address: 173.179.179.8
[INFO ] 2019-01-19 10:29:10.004 [           main] o.a.j.c.t.c.ConnectionHandler: Ip reported to tracker will be: 173.179.179.8
[INFO ] 2019-01-19 10:29:10.133 [           main] o.a.j.c.c.JoalConfigProvider: App configuration has been successfully loaded.
[INFO ] 2019-01-19 10:29:30.022 [torrent-file-watcher-0] o.a.j.c.t.w.TorrentFileProvider: Torrent file addition detected, hot creating file: ~/.config/joal/torrents/linux.torrent
[INFO ] 2019-01-19 10:29:30.048 [torrent-file-watcher-0] c.t.t.c.Torrent: Multi-file torrent information:
[INFO ] 2019-01-19 10:29:30.049 [torrent-file-watcher-0] c.t.t.c.Torrent:   Torrent name: Linux
[INFO ] 2019-01-19 10:29:30.049 [torrent-file-watcher-0] c.t.t.c.Torrent:   Announced at:
[INFO ] 2019-01-19 10:29:30.049 [torrent-file-watcher-0] c.t.t.c.Torrent:      1. https://www.tracker.com/announce?passkey=<HIDDEN>
[INFO ] 2019-01-19 10:29:30.050 [torrent-file-watcher-0] c.t.t.c.Torrent:   Created on..: 2019-01-01T01:51:22.000-0500
[INFO ] 2019-01-19 10:29:30.051 [torrent-file-watcher-0] c.t.t.c.Torrent:   Created by..: ruTorrent (PHP Class - Adrien Gibrat)
[INFO ] 2019-01-19 10:29:30.051 [torrent-file-watcher-0] c.t.t.c.Torrent:   Found 2 file(s) in multi-file torrent structure.
[INFO ] 2019-01-19 10:29:30.051 [torrent-file-watcher-0] c.t.t.c.Torrent:   Pieces......: 137 piece(s) (8388608 byte(s)/piece)
[INFO ] 2019-01-19 10:29:30.052 [torrent-file-watcher-0] c.t.t.c.Torrent:   Total size..: 1 144 890 770 byte(s)
[INFO ] 2019-01-19 10:29:37.456 [   annnouncer-0] o.a.j.c.t.c.a.Announcer: ³¤ðáÐdIê|!CÀä{¶ has announced successfully. Response: 10 seeders, 0 leechers, 1800s interval
[WARN ] 2019-01-19 10:59:37.673 [   annnouncer-1] o.a.j.c.t.c.a.Announcer: ³¤ðáÐdIê|!CÀä{¶ has failed to announce
com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:57)
	at org.araymond.joal.core.ttorrent.client.announcer.Announcer.announce(Announcer.java:63)
	at org.araymond.joal.core.ttorrent.client.announcer.request.AnnouncerExecutor.lambda$execute$0(AnnouncerExecutor.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:93)
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:44)
	... 6 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.http.client.fluent.Request.internalExecute(Request.java:173)
	at org.apache.http.client.fluent.Request.execute(Request.java:177)
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:89)
	... 7 more





[WARN ] 2019-01-19 11:29:37.869 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: ³¤ðáÐdIê|!CÀä{¶ has failed to announce
com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:57)
	at org.araymond.joal.core.ttorrent.client.announcer.Announcer.announce(Announcer.java:63)
	at org.araymond.joal.core.ttorrent.client.announcer.request.AnnouncerExecutor.lambda$execute$0(AnnouncerExecutor.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:93)
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:44)
	... 6 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.http.client.fluent.Request.internalExecute(Request.java:173)
	at org.apache.http.client.fluent.Request.execute(Request.java:177)
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:89)
	... 7 more
^C[INFO ] 2019-01-19 11:30:19.140 [       Thread-2] o.a.j.ApplicationClosingListener: Gracefully shutting down application.
[WARN ] 2019-01-19 11:30:19.200 [   annnouncer-0] o.a.j.c.t.c.a.Announcer: ³¤ðáÐdIê|!CÀä{¶ has failed to announce
com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:57)
	at org.araymond.joal.core.ttorrent.client.announcer.Announcer.announce(Announcer.java:63)
	at org.araymond.joal.core.ttorrent.client.announcer.request.AnnouncerExecutor.lambda$execute$0(AnnouncerExecutor.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:93)
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:44)
	... 6 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.http.client.fluent.Request.internalExecute(Request.java:173)
	at org.apache.http.client.fluent.Request.execute(Request.java:177)
	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:89)
	... 7 more
[INFO ] 2019-01-19 11:30:19.203 [       Thread-3] o.a.j.c.t.c.ConnectionHandler: Ip fetcher thread has been stopped.
[INFO ] 2019-01-19 11:30:19.215 [       Thread-2] o.a.j.ApplicationClosingListener: JOAL gracefully shut down.
[INFO ] 2019-01-19 11:30:19.221 [       Thread-2] o.s.s.c.ThreadPoolTaskExecutor: Shutting down ExecutorService 'taskExecutor'
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (jar:file:/tmp/joal/jack-of-all-trades-2.1.11.jar!/BOOT-INF/lib/tomcat-embed-core-9.0.12.jar!/) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
Thanks for your help.

**Comment by anthonyraymond** [comment]
What version of java are you using? I would recommend at least java 8u161

**Comment by anthonyraymond** [comment]
Closing due to no response. Let me know if you still have problem with it

**Comment by antoyo** [comment]
Well, I don't get the errors anymore with an older version of java (Java 8), but the tracker does not receive the actual uploaded data.

**Comment by anthonyraymond** [comment]
Does your torent has peers in the joal webui?
and does the torrent display an actual upload speed?
