### ISSUE TITLE
[INFO ] 2019-02-18 01:33:39.963 [           main] o.a.j.ApplicationClosingListener: JOAL gracefully shut down.

### ISSUE THREAD

**Issue by a6640002** [anthonyraymond/joal#58]
[ERROR] 2019-02-18 01:33:39.902 [           main] o.a.j.ApplicationReadyListener: Fatal error encountered
java.lang.IllegalStateException: Fatal error encountered
        at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:37)
        at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:17)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
        at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:105)
        at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at org.araymond.joal.JackOfAllTradesApplication.main(JackOfAllTradesApplication.java:16)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3236)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
        at java.io.OutputStream.write(OutputStream.java:75)
        at com.turn.ttorrent.bcodec.BEncoder.bencode(BEncoder.java:92)
        at com.turn.ttorrent.bcodec.BEncoder.bencode(BEncoder.java:71)
        at com.turn.ttorrent.bcodec.BEncoder.bencode(BEncoder.java:108)
        at com.turn.ttorrent.common.Torrent.<init>(Torrent.java:144)
        at org.araymond.joal.core.torrent.torrent.MockedTorrent.<init>(MockedTorrent.java:35)
        at org.araymond.joal.core.torrent.torrent.MockedTorrent.fromFile(MockedTorrent.java:57)
        at org.araymond.joal.core.torrent.watcher.TorrentFileProvider.onFileCreate(TorrentFileProvider.java:90)
        at org.araymond.joal.core.torrent.watcher.TorrentFileWatcher$$Lambda$372/895281180.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.araymond.joal.core.torrent.watcher.TorrentFileWatcher.start(TorrentFileWatcher.java:57)
        at org.araymond.joal.core.torrent.watcher.TorrentFileProvider.start(TorrentFileProvider.java:49)
        at org.araymond.joal.core.SeedManager.init(SeedManager.java:61)
        at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:34)
        at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:17)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
        at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:105)
        at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at org.araymond.joal.JackOfAllTradesApplication.main(JackOfAllTradesApplication.java:16)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO ] 2019-02-18 01:33:39.943 [           main] o.a.j.ApplicationClosingListener: Gracefully shutting down application.
[INFO ] 2019-02-18 01:33:39.947 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Ip fetcher thread has been stopped.
[INFO ] 2019-02-18 01:33:39.963 [           main] o.a.j.ApplicationClosingListener: JOAL gracefully shut down.

The program crashed.Is there insufficient memory?

**Comment by a6640002** [comment]
The problem has been solved. Just because the memory is too large, delete some  torrents is ok. when  i keep 80 torrents,its crash,when i delete to 70 its ok now

**Comment by anthonyraymond** [comment]
Mine do runs more than 200. What you may want to run the program with more memory.

See https://stackoverflow.com/questions/1565388/increase-heap-size-in-java
