### ISSUE TITLE
No more valid tracker URI

### ISSUE THREAD

**Issue by BSSI1** [anthonyraymond/joal#64]
so i was just about to test this with random file from public tracker and I can't get pass this error...

```[INFO ] 2019-03-26 14:26:22.015 [   annnouncer-1] o.a.j.c.t.c.a.Announcer: 2I©(u:sµyÌµuý¬Á has failed to announce 5 times in a raw
[INFO ] 2019-03-26 14:26:22.024 [   annnouncer-1] o.a.j.c.t.w.TorrentFileProvider: Torrent file deleting detected, hot deleted file: C:\Users\Username\temp\config.json\torrents\3249B82875863A7316E69D9D79DEE67516ECAAB5.torrent
[INFO ] 2019-03-26 14:26:22.026 [   annnouncer-1] o.a.j.c.t.w.TorrentFileProvider: Successfully moved file: C:\Users\Jernej\temp\config.json\torrents\3249B82875863A7316E69D9D79DEE67516ECAAB5.torrent to archive folder
[WARN ] 2019-03-26 14:26:47.491 [http-nio-1234-exec-9] o.a.j.w.c.o.AbortNonPrefixedRequestFilter: Request was sent to URI '/' and does not match the path prefix, therefore the request Thread has been shut down.
[INFO ] 2019-03-26 14:26:53.905 [torrent-file-watcher-0] o.a.j.c.t.w.TorrentFileProvider: Torrent file addition detected, hot creating file: C:\Users\Jernej\temp\config.json\torrents\3249B82875863A7316E69D9D79DEE67516ECAAB5.torrent
[INFO ] 2019-03-26 14:26:53.908 [torrent-file-watcher-0] c.t.t.c.Torrent: Multi-file torrent information:
[INFO ] 2019-03-26 14:26:53.908 [torrent-file-watcher-0] c.t.t.c.Torrent:   Torrent name: A Dog's Way Home (2019) [WEBRip] [720p] [YTS.AM]
[INFO ] 2019-03-26 14:26:53.909 [torrent-file-watcher-0] c.t.t.c.Torrent:   Announced at:
[INFO ] 2019-03-26 14:26:53.909 [torrent-file-watcher-0] c.t.t.c.Torrent:      1. udp://tracker.coppersurfer.tk:6969/announce
[INFO ] 2019-03-26 14:26:53.910 [torrent-file-watcher-0] c.t.t.c.Torrent:      2. udp://9.rarbg.com:2710/announce
[INFO ] 2019-03-26 14:26:53.910 [torrent-file-watcher-0] c.t.t.c.Torrent:      3. udp://p4p.arenabg.com:1337
[INFO ] 2019-03-26 14:26:53.911 [torrent-file-watcher-0] c.t.t.c.Torrent:      4. udp://tracker.internetwarriors.net:1337
[INFO ] 2019-03-26 14:26:53.911 [torrent-file-watcher-0] c.t.t.c.Torrent:      5. udp://tracker.opentrackr.org:1337/announce
[INFO ] 2019-03-26 14:26:53.911 [torrent-file-watcher-0] c.t.t.c.Torrent:   Created on..: 2019-03-25T15:31:07.000+0100
[INFO ] 2019-03-26 14:26:53.912 [torrent-file-watcher-0] c.t.t.c.Torrent:   Comment.....: Torrent downloaded from https://yts.am ( former: https://yts.ag )
[INFO ] 2019-03-26 14:26:53.912 [torrent-file-watcher-0] c.t.t.c.Torrent:   Created by..: YTS.AG
[INFO ] 2019-03-26 14:26:53.912 [torrent-file-watcher-0] c.t.t.c.Torrent:   Found 2 file(s) in multi-file torrent structure.
[INFO ] 2019-03-26 14:26:53.913 [torrent-file-watcher-0] c.t.t.c.Torrent:   Pieces......: 1638 piece(s) (524288 byte(s)/piece)
[INFO ] 2019-03-26 14:26:53.913 [torrent-file-watcher-0] c.t.t.c.Torrent:   Total size..: 858,766,468 byte(s)
[WARN ] 2019-03-26 14:26:55.033 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: 2I©(u:sµyÌµuý¬Á has failed to announce
com.turn.ttorrent.client.announce.AnnounceException: No more valid tracker URI
        at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:39)
        at org.araymond.joal.core.ttorrent.client.announcer.Announcer.announce(Announcer.java:63)
        at org.araymond.joal.core.ttorrent.client.announcer.request.AnnouncerExecutor.lambda$execute$0(AnnouncerExecutor.java:40)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.araymond.joal.core.ttorrent.client.announcer.tracker.NoMoreUriAvailableException: No more valid trackers
        at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClientUriProvider.moveToNext(TrackerClientUriProvider.java:39)
        at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClientUriProvider.deleteCurrentAndMoveToNext(TrackerClientUriProvider.java:34)
        at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:35)
        ... 6 more```

any ideas?

**Comment by anthonyraymond** [comment]
Hi,

As most public trackers they only use UDP protocol :
```
[INFO ] 2019-03-26 14:26:53.909 [torrent-file-watcher-0] c.t.t.c.Torrent:      1. udp://tracker.coppersurfer.tk:6969/announce
[INFO ] 2019-03-26 14:26:53.910 [torrent-file-watcher-0] c.t.t.c.Torrent:      2. udp://9.rarbg.com:2710/announce
[INFO ] 2019-03-26 14:26:53.910 [torrent-file-watcher-0] c.t.t.c.Torrent:      3. udp://p4p.arenabg.com:1337
[INFO ] 2019-03-26 14:26:53.911 [torrent-file-watcher-0] c.t.t.c.Torrent:      4. udp://tracker.internetwarriors.net:1337
[INFO ] 2019-03-26 14:26:53.911 [torrent-file-watcher-0] c.t.t.c.Torrent:      5. udp://tracker.opentrackr.org:1337/announce
```

Joal does not support UDP at this time. 99% of private trackers uses HTTP or HTTPS so i've skipped it. If you want to try a public torrent try these ones from ubuntu : https://www.ubuntu.com/download/alternative-downloads#bittorrent

**Comment by anthonyraymond** [comment]
Close due to no answer and expected behavior

**Comment by johnb789** [comment]
Please support UDP, it's much easier for me to just use a public tracker than set up my own private tracker.

**Comment by anthonyraymond** [comment]
@johnb789 what ? Why would you use joal on public trackers?
