### ISSUE TITLE
Fatal error encountered

### ISSUE THREAD

**Issue by adrienpsn** [anthonyraymond/joal#65]
```
java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

Command:
```
java -jar joal/jack-of-all-trades-2.1.14.jar --joal-conf=joal-conf/ --spring.main.web-environment=true --server.port=8000 --joal.ui.path.prefix=password --joal.ui.secret-token=password
```

Error:
```
[ERROR] 2019-03-29 21:19:07.187 [           main] o.a.j.ApplicationReadyListener: Fatal error encountered
java.lang.IllegalStateException: Fatal error encountered
	at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:37)
	at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:17)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:105)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.araymond.joal.JackOfAllTradesApplication.main(JackOfAllTradesApplication.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.io.FileNotFoundException: BitTorrent client configuration file '/Users/adrien/Documents/JOAL/joal-conf/clients/qbittorrent-3.3.16.client' not found.
	at org.araymond.joal.core.client.emulated.BitTorrentClientProvider.generateNewClient(BitTorrentClientProvider.java:64)
	at org.araymond.joal.core.SeedManager.startSeeding(SeedManager.java:92)
	at org.araymond.joal.ApplicationReadyListener.onApplicationEvent(ApplicationReadyListener.java:35)
	... 20 more
[INFO ] 2019-03-29 21:19:07.188 [           main] o.a.j.ApplicationClosingListener: Gracefully shutting down application.
[INFO ] 2019-03-29 21:19:07.189 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Ip fetcher thread has been stopped.
[INFO ] 2019-03-29 21:19:07.201 [           main] o.a.j.ApplicationClosingListener: JOAL gracefully shut down.
```

What's the problem?

**Comment by anthonyraymond** [comment]
You did not setted up the app properly. There is nothing in your /Users/adrien/Documents/JOAL/joal-conf/clients/ folder, or at least `qbittorrent-3.3.16.client` is missing

**Comment by adrienpsn** [comment]
> You did not setted up the app properly. There is nothing in your /Users/adrien/Documents/JOAL/joal-conf/clients/ folder, or at least `qbittorrent-3.3.16.client` is missing


```
cat joal-conf/config.json
{
  "minUploadRate" : 30,
  "maxUploadRate" : 160,
  "simultaneousSeed" : 20,
  "client" : "qbittorrent-3.3.1.client",
  "keepTorrentWithZeroLeechers" : true
}
```

```
ls joal-conf/clients/
qbitorrent-3.3.1.client
```

**Comment by anthonyraymond** [comment]
`qbittorrent-3.3.16.client`
vs
`qbitorrent-3.3.1.client`

Either set the config to 3.3.1 or add the 3.3.16 client file to your folder version 😉

**Comment by adrienpsn** [comment]
> `qbittorrent-3.3.16.client`
> vs
> `qbitorrent-3.3.1.client`
> 
> Either set the config to 3.3.1 or add the 3.3.16 client file to your clients folder 😉 Also, there is a typo in your config, `qbittorrent` requires two `t`.

Ok in fact it was the typo in `config.json` file...

Thank you for your help!

**Comment by anthonyraymond** [comment]
No problem
