### ISSUE TITLE
Failing to announce torrent (java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty)

### ISSUE THREAD

**Issue by pcoutinho** [anthonyraymond/joal#75]
Hi, first of all, thank you very much for this amazing piece of software. I've been using it on my laptop (desktop version) and it has been working great.

I'm trying to setup a RaspberryPi with Joal and everything seems to be up and running, however, it is failing to announce torrents for some reason. Same torrents work on my laptop but not on the server.

Here is the log

```
[WARN ] 2019-06-24 21:18:15.979 [   annnouncer-0] o.a.j.c.t.c.a.Announcer: ATSmyÇÎKÈº^µÀRL® has failed to announce
Jun 24 21:18:15 raspberrypi java[2734]: com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.
Jun 24 21:18:15 raspberrypi java[2734]:         at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:57)
Jun 24 21:18:15 raspberrypi java[2734]:         at org.araymond.joal.core.ttorrent.client.announcer.Announcer.announce(Announcer.java:63)
Jun 24 21:18:15 raspberrypi java[2734]:         at org.araymond.joal.core.ttorrent.client.announcer.request.AnnouncerExecutor.lambda$execute$0(AnnouncerExecutor.java:40)
Jun 24 21:18:15 raspberrypi java[2734]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Jun 24 21:18:15 raspberrypi java[2734]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
Jun 24 21:18:15 raspberrypi java[2734]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
Jun 24 21:18:15 raspberrypi java[2734]:         at java.base/java.lang.Thread.run(Thread.java:844)
Jun 24 21:18:15 raspberrypi java[2734]: Caused by: com.turn.ttorrent.client.announce.AnnounceException: Failed to announce: error or connection aborted.
Jun 24 21:18:15 raspberrypi java[2734]:         at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:93)
Jun 24 21:18:15 raspberrypi java[2734]:         at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:44)
Jun 24 21:18:15 raspberrypi java[2734]:         ... 6 more
Jun 24 21:18:15 raspberrypi java[2734]: Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter mu
Jun 24 21:18:15 raspberrypi java[2734]:         at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
Jun 24 21:18:15 raspberrypi java[2734]:         at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1969)
Jun 24 21:18:15 raspberrypi java[2734]:         at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1921)
Jun 24 21:18:15 raspberrypi java[2734]:         at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1904)
Jun 24 21:18:15 raspberrypi java[2734]:         at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1436)
Jun 24 21:18:15 raspberrypi java[2734]:         at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
Jun 24 21:18:15 raspberrypi java[2734]:         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
Jun 24 21:18:16 raspberrypi java[2734]:         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
Jun 24 21:18:16 raspberrypi java[2734]:         at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
Jun 24 21:18:16 raspberrypi java[2734]:         at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
Jun 24 21:18:16 raspberrypi java[2734]:         at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
Jun 24 21:18:16 raspberrypi java[2734]:         at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
Jun 24 21:18:16 raspberrypi java[2734]:         at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
Jun 24 21:18:16 raspberrypi java[2734]:         at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
Jun 24 21:18:16 raspberrypi java[2734]:         at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
Jun 24 21:18:16 raspberrypi java[2734]:         at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
Jun 24 21:18:16 raspberrypi java[2734]:         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
Jun 24 21:18:16 raspberrypi java[2734]:         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
Jun 24 21:18:16 raspberrypi java[2734]:         at org.apache.http.client.fluent.Request.internalExecute(Request.java:173)
Jun 24 21:18:16 raspberrypi java[2734]:         at org.apache.http.client.fluent.Request.execute(Request.java:177)
Jun 24 21:18:16 raspberrypi java[2734]:         at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:89)
Jun 24 21:18:16 raspberrypi java[2734]:         ... 7 more
Jun 24 21:18:16 raspberrypi java[2734]: Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:330)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:180)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:192)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:133)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1825)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1655)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:260)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.ssl.Handshaker.processLoop(Handshaker.java:1086)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.ssl.Handshaker.processRecord(Handshaker.java:1020)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(SSLSocketImpl.java:1137)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
Jun 24 21:18:16 raspberrypi java[2734]:         ... 23 more
Jun 24 21:18:16 raspberrypi java[2734]: Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
Jun 24 21:18:16 raspberrypi java[2734]:         at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:86)
Jun 24 21:18:16 raspberrypi java[2734]:         ... 38 more
```

This is running on Raspbian and manual install (no docker). And I'm glad to give more info if needed.

**Comment by anthonyraymond** [comment]
Hi :)
Thanks, i'm glad you like it.

There couls be various reasons for this error. It means that java does not foud or can't open th keystore.


Try to install the "ca-certificates" package, if it does not work let me know what version of java you are running "java -version"


Le 24 juin 2019 à 22:41, à 22:41, Pedro Coutinho <notifications@github.com> a écrit:

**Comment by pcoutinho** [comment]
ca-certificates is already installed and is the latest version.

And java is:

java --version

openjdk 9-Raspbian
OpenJDK Runtime Environment (build 9-Raspbian+0-9b181-4bpo9rpt1)
OpenJDK Server VM (build 9-Raspbian+0-9b181-4bpo9rpt1, mixed mode)

**Comment by anthonyraymond** [comment]
Can you try with a openjdk 8 ? 

OpenJdk 9 seems to have some funky issues regarding keystore.

I've found this on a forum:


>Work-around:
>$ sudo apt install openjdk-8-jre
>$ sudo rm /etc/ssl/certs/java/cacerts
>$ sudo update-ca-certificates --fresh
>
>This works because /etc/ca-certificates/update.d/jks-keystore prefers OpenJDK 8 over OpenJDK 9.

**Comment by pcoutinho** [comment]
So I've reinstalled Raspbian with the latest version (Debian Buster) and it
works fine now! :)

Running OpenJDK 11.

So if there aren't any more people with this issue I think it can be
closed. Thank you so much for your help and this amazing software!

**Comment by anthonyraymond** [comment]
Nice 😃

Thanks for your support.
